### ISSUE TITLE
Pivot table extra attributes

### ISSUE THREAD

**Issue by tlgreg** [XCMer/larry-four-generator#3]
Would nice to be able to define extra columns for pivot tables somewhere. Or override the automatic pivot table somehow for a relationship.
Or I am missing something? :)

**Comment by XCMer** [comment]
I'll have to think about how to punch this feature in. I'll figure something out for the next stable release (after 1.0)

**Comment by XCMer** [comment]
I've just added support for orphan tables in Larry (a separate branch called tabledefs). Basically, it allows you to just define a table without generating any models/relationships for it.

I'll be adding a new relationship type that would be like belongsToMany, but will not create a pivot table. Instead, it will assume that you would create a table definition yourself.

Since everything is well tested (thanks to TDD), I'm pushing for this feature in 1.0stable itself.

**Comment by XCMer** [comment]
This feature has been implemented in branch tabledefs. I'll merge it in for the final release of version 1.0. It'd look something like:

```
Post; mm Image imageable; btmc Comment;
    timestamps
    title string 250
    content text
    rating decimal 5 2

table comment_post
    id increments
    comment_id integer; unsigned
    post_id integer; unsigned
    additional fields...
```

Notice 'btmc' (belongsToMany Custom) instead of 'btm'. It still can take the same parameters as 'btm', which is the pivot table name and the column overrides. It'll do some error checking (like if you forgot to create the pivot table, it'll let you know that it is not present).

Notice the "table comment_post" syntax. Anything that starts with "table" tells Larry that you want to create an orphan table, but don't want any relations/models to be created.

**Comment by tlgreg** [comment]
Nice, thanks!

**Comment by XCMer** [comment]
Larry Four 1.0.0 Stable has been released with this feature included.
